Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
Wed Apr  6 07:29:29 GMT 2022
jlab.py:30: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif dashinfo is not '0':
jlab.py:33: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if dashinfo is not '0':
[I 2022-04-06 07:29:56.928 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-04-06 07:29:56.944 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-04-06 07:29:56.952 ServerApp] nbclassic | extension was successfully linked.
[I 2022-04-06 07:30:02.702 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-04-06 07:30:03.357 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-04-06 07:30:03.358 LabApp] JupyterLab extension loaded from /home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/jupyterlab
[I 2022-04-06 07:30:03.358 LabApp] JupyterLab application directory is /home1/datahome/mdemol/.miniconda3/envs/m2env/share/jupyter/lab
[I 2022-04-06 07:30:03.362 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-04-06 07:30:03.466 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-04-06 07:30:03.466 ServerApp] Serving notebooks from local directory: /home1/datahome/mdemol
[I 2022-04-06 07:30:03.466 ServerApp] Jupyter Server 1.16.0 is running at:
[I 2022-04-06 07:30:03.466 ServerApp] http://r1i2n17:8877/lab
[I 2022-04-06 07:30:03.466 ServerApp]  or http://127.0.0.1:8877/lab
[I 2022-04-06 07:30:03.466 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2022-04-06 07:34:46.993 ServerApp] 302 GET / (10.148.1.145) 0.47ms
[I 2022-04-06 07:34:54.720 LabApp] Build is up to date
[W 2022-04-06 07:34:58.529 ServerApp] Notebook m2_2022/sandbox/overview.ipynb is not trusted
[I 2022-04-06 07:35:01.129 ServerApp] Kernel started: 8adb755e-783c-49e0-84fa-b5095befb736
readline: /etc/inputrc: line 19: term: unknown variable name
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 81e96d40-546a-440e-93f1-386d34df1735
[I 2022-04-06 07:45:02.990 ServerApp] Saving file at /m2_2022/sandbox/overview.ipynb
[W 2022-04-06 07:45:02.992 ServerApp] Notebook m2_2022/sandbox/overview.ipynb is not trusted
[I 2022-04-06 08:03:03.083 ServerApp] Saving file at /m2_2022/sandbox/overview.ipynb
[W 2022-04-06 08:03:03.084 ServerApp] Notebook m2_2022/sandbox/overview.ipynb is not trusted
[I 2022-04-06 08:05:03.210 ServerApp] Saving file at /m2_2022/sandbox/overview.ipynb
[W 2022-04-06 08:05:03.212 ServerApp] Notebook m2_2022/sandbox/overview.ipynb is not trusted
[I 2022-04-06 08:43:04.267 ServerApp] Saving file at /m2_2022/sandbox/overview.ipynb
[W 2022-04-06 08:43:04.268 ServerApp] Notebook m2_2022/sandbox/overview.ipynb is not trusted
[I 2022-04-06 08:45:04.463 ServerApp] Saving file at /m2_2022/sandbox/overview.ipynb
[W 2022-04-06 08:45:04.464 ServerApp] Notebook m2_2022/sandbox/overview.ipynb is not trusted
[I 2022-04-06 08:46:03.448 ServerApp] Kernel interrupted: 8adb755e-783c-49e0-84fa-b5095befb736
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
[I 2022-04-06 08:46:09.567 ServerApp] Kernel interrupted: 8adb755e-783c-49e0-84fa-b5095befb736
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/contextlib.py:120: UserWarning: Creating scratch directories is taking a surprisingly long time. This is often due to running workers on a network file system. Consider specifying a local-directory to point workers to write scratch data to a local disk.
  next(self.gen)
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/process.py", line 175, in _run
    target(*args, **kwargs)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/nanny.py", line 836, in _run
    worker = Worker(**worker_kwargs)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/worker.py", line 611, in __init__
    self._workdir = self._workspace.new_work_dir(prefix="worker-")
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/diskutils.py", line 248, in new_work_dir
    return WorkDir(self, **kwargs)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/diskutils.py", line 61, in __init__
    with workspace._global_lock():
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/locket.py", line 197, in __enter__
    self.acquire()
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/locket.py", line 191, in acquire
    self._lock.acquire(self._timeout, self._retry_period)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/locket.py", line 120, in acquire
    lock.acquire(timeout, retry_period)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/locket.py", line 164, in acquire
    _lock_file_blocking(self._file)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/locket.py", line 60, in _lock_file_blocking
    fcntl.flock(file_.fileno(), fcntl.LOCK_EX)
KeyboardInterrupt
Process Dask Worker process (from Nanny):
Traceback (most recent call last):
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/process.py", line 175, in _run
    target(*args, **kwargs)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/nanny.py", line 836, in _run
    worker = Worker(**worker_kwargs)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/worker.py", line 611, in __init__
    self._workdir = self._workspace.new_work_dir(prefix="worker-")
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/diskutils.py", line 248, in new_work_dir
    return WorkDir(self, **kwargs)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/diskutils.py", line 61, in __init__
    with workspace._global_lock():
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/locket.py", line 197, in __enter__
    self.acquire()
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/locket.py", line 191, in acquire
    self._lock.acquire(self._timeout, self._retry_period)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/locket.py", line 120, in acquire
    lock.acquire(timeout, retry_period)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/locket.py", line 164, in acquire
    _lock_file_blocking(self._file)
  File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/distributed/locket.py", line 60, in _lock_file_blocking
    fcntl.flock(file_.fileno(), fcntl.LOCK_EX)
KeyboardInterrupt
[I 2022-04-06 08:47:04.660 ServerApp] Saving file at /m2_2022/sandbox/overview.ipynb
[W 2022-04-06 08:47:04.661 ServerApp] Notebook m2_2022/sandbox/overview.ipynb is not trusted
[I 2022-04-06 09:13:43.670 ServerApp] 302 GET / (10.148.1.145) 0.32ms
[I 2022-04-06 09:45:37.503 ServerApp] Saving file at /m2_2022/sandbox/overview.ipynb
[W 2022-04-06 09:45:37.505 ServerApp] Notebook m2_2022/sandbox/overview.ipynb is not trusted
[I 2022-04-06 09:55:37.709 ServerApp] Saving file at /m2_2022/sandbox/overview.ipynb
[W 2022-04-06 09:55:37.710 ServerApp] Notebook m2_2022/sandbox/overview.ipynb is not trusted
[I 2022-04-06 09:57:37.902 ServerApp] Saving file at /m2_2022/sandbox/overview.ipynb
[W 2022-04-06 09:57:37.902 ServerApp] Notebook m2_2022/sandbox/overview.ipynb is not trusted
[I 2022-04-06 09:59:04.301 ServerApp] Saving file at /m2_2022/sandbox/overview.ipynb
[W 2022-04-06 09:59:04.302 ServerApp] Notebook m2_2022/sandbox/overview.ipynb is not trusted
[I 2022-04-06 10:00:16.242 ServerApp] Kernel shutdown: 8adb755e-783c-49e0-84fa-b5095befb736
[I 2022-04-06 10:00:18.896 ServerApp] Shutting down on /api/shutdown request.
[I 2022-04-06 10:00:18.897 ServerApp] Shutting down 3 extensions
[I 2022-04-06 10:00:18.898 ServerApp] Shutting down 0 kernels
[I 2022-04-06 10:00:18.898 ServerApp] Shutting down 0 terminals
Terminated
