Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
Mon Aug 22 15:55:31 GMT 2022
jlab.py:30: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  elif dashinfo is not '0':
jlab.py:33: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if dashinfo is not '0':
[I 2022-08-22 15:56:05.955 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-08-22 15:56:05.965 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-08-22 15:56:05.973 ServerApp] nbclassic | extension was successfully linked.
[I 2022-08-22 15:56:14.113 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-08-22 15:56:15.012 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-08-22 15:56:15.013 LabApp] JupyterLab extension loaded from /home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/jupyterlab
[I 2022-08-22 15:56:15.013 LabApp] JupyterLab application directory is /home1/datahome/mdemol/.miniconda3/envs/m2env/share/jupyter/lab
[I 2022-08-22 15:56:15.017 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-08-22 15:56:15.139 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-08-22 15:56:15.139 ServerApp] Serving notebooks from local directory: /home1/datahome/mdemol
[I 2022-08-22 15:56:15.139 ServerApp] Jupyter Server 1.16.0 is running at:
[I 2022-08-22 15:56:15.139 ServerApp] http://r1i2n13:8877/lab
[I 2022-08-22 15:56:15.139 ServerApp]  or http://127.0.0.1:8877/lab
[I 2022-08-22 15:56:15.139 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2022-08-22 15:56:53.306 LabApp] Build is up to date
[W 2022-08-22 15:57:00.657 ServerApp] Notebook m2_2022/sandbox/diag_pdf_ind.ipynb is not trusted
[E 2022-08-22 15:57:10.079 LabApp] Fail to get yarn configuration. Error: ENOENT: no such file or directory, open '/home1/package.json'
        at Object.openSync (node:fs:585:3)
        at Object.readFileSync (node:fs:453:35)
        at onUnexpectedError (/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:100386:108)
        at /home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:100505:9
    
[I 2022-08-22 15:57:10.087 LabApp] Build is up to date
[E 2022-08-22 15:57:28.111 ServerApp] Uncaught exception GET /lab/api/settings/@jupyterlab/htmlviewer-extension:plugin?1661183847974 (10.148.1.145)
    HTTPServerRequest(protocol='http', host='localhost:8877', method='GET', uri='/lab/api/settings/@jupyterlab/htmlviewer-extension:plugin?1661183847974', version='HTTP/1.1', remote_ip='10.148.1.145')
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
    tornado.iostream.StreamClosedError: Stream is closed
[E 2022-08-22 15:57:28.141 ServerApp] Uncaught exception GET /lab/api/settings/@jupyterlab/notebook-extension:panel?1661183847975 (10.148.1.145)
    HTTPServerRequest(protocol='http', host='localhost:8877', method='GET', uri='/lab/api/settings/@jupyterlab/notebook-extension:panel?1661183847975', version='HTTP/1.1', remote_ip='10.148.1.145')
    Traceback (most recent call last):
      File "/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
    tornado.iostream.StreamClosedError: Stream is closed
[E 2022-08-22 15:57:31.024 LabApp] Fail to get yarn configuration. Error: ENOENT: no such file or directory, open '/home1/package.json'
        at Object.openSync (node:fs:585:3)
        at Object.readFileSync (node:fs:453:35)
        at onUnexpectedError (/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:100386:108)
        at /home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:100505:9
    
[I 2022-08-22 15:57:31.031 LabApp] Build is up to date
[E 2022-08-22 15:57:35.912 LabApp] Fail to get yarn configuration. Error: ENOENT: no such file or directory, open '/home1/package.json'
        at Object.openSync (node:fs:585:3)
        at Object.readFileSync (node:fs:453:35)
        at onUnexpectedError (/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:100386:108)
        at /home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:100505:9
    
[I 2022-08-22 15:57:35.919 LabApp] Build is up to date
[E 2022-08-22 15:57:51.813 LabApp] Fail to get yarn configuration. Error: ENOENT: no such file or directory, open '/home1/package.json'
        at Object.openSync (node:fs:585:3)
        at Object.readFileSync (node:fs:453:35)
        at onUnexpectedError (/home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:100386:108)
        at /home1/datahome/mdemol/.miniconda3/envs/m2env/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:100505:9
    
[I 2022-08-22 15:57:51.821 LabApp] Build is up to date
[W 2022-08-22 15:58:18.951 ServerApp] Notebook m2_2022/sandbox/diag_pdf_ind.ipynb is not trusted
Terminated
[C 2022-08-23 11:53:36.025 ServerApp] received signal 15, stopping
[I 2022-08-23 11:53:36.096 ServerApp] Shutting down 3 extensions
[I 2022-08-23 11:53:36.097 ServerApp] Shutting down 0 kernels
[I 2022-08-23 11:53:36.097 ServerApp] Shutting down 0 terminals
